### ISSUE TITLE
Use default xinitrc

### ISSUE THREAD

**Issue by rapgro** [joukewitteveen/xlogin#11]
If there's no custom ~/.xinitrc available, xlogin should look for /etc/X11/xinit/xinitrc automatically. Currently, it's needed to use a symlink at least.

**Comment by joukewitteveen** [comment]
Why should it look for that file? xlogin is not `xinit`. It does not require it and does not strive at being compatible (I currently think using `.xinit` was a mistake and I should have gone with `.xlogin`). Indeed, both are very similar and in many cases a `.xinit` script can be used with both packages.

Of course, if there is a good reason to support a fallback default file, we should use it. However, without it everything is simple and predictable. `systemd` provides enough surprises by itself, let's not introduce the potential for more ;-).

**Comment by rapgro** [comment]
Well, that means a configuration effort for downstream, e.g. if my package gets installed in Fedora. And generally, I doubt xlogin can work for more than one user in parallel.

**Comment by joukewitteveen** [comment]
But we cannot even guarantee that it will work with any `/etc/X11/xinit/xinitrc` supplied by a third party (`xinit` that is). The problem is that the xlogin version of `.xinitrc` must not return. I don't remember this being a necessary requirement of the xinit version.
