### ISSUE TITLE
systemd restarts xlogin periodically

### ISSUE THREAD

**Issue by avbop** [joukewitteveen/xlogin#13]
Every so often (seemingly on the hour, according to the log), systemd restarts the xlogin service. X keeps running, but my .xinitrc gets re-executed (eg another Firefox window opens, since I run `firefox` via .xinitrc). I'm running Arch Linux.

(I've also seen issues with xmonad from about the same time as this started (after updating a couple days ago), but those issues usually crash X entirely, which is not what happens here.)

[xlogin.txt](https://github.com/joukewitteveen/xlogin/files/712432/xlogin.txt)

**Comment by avbop** [comment]
I'd forgotten I needed to manually update this package, and the most recent version works fine. Very sorry to have bothered you.

**Comment by joukewitteveen** [comment]
Do make sure that your `.xinitrc` does _not_ return.
