### ISSUE TITLE
Lot's of issues in my Xorg log

### ISSUE THREAD

**Issue by rambip** [joukewitteveen/xlogin#14]
I noticed that some of my key didn't work after I start the X server with the service.

When I checked my .local/share/xorg/Xorg.0.log, I saw many warnings, for example 
`[   122.425] (II) UnloadModule: "libinput"`

Is this a bug ?

**Comment by joukewitteveen** [comment]
I have no reason to believe this has anything to do with `xlogin`. Maybe your systemd journal provides more useful output.

That being said, you stand a better chance getting useful troubleshooting help on a forum. Of course, if you do find an issue with `xlogin`, this tracker is the right place to report the issues you find.

**Comment by rambip** [comment]
Indeed, it may be an issue with i3, my window manager
the alt+space combination doesn't work after I switch layout

**Comment by rambip** [comment]
But I have a question that can be related:
Does xlogin source the .bashrc before calling X ?

This can cause issues depending on what is set in my path ...

**Comment by joukewitteveen** [comment]
A login shell is started in https://github.com/joukewitteveen/xlogin/blob/master/xlogin%40.service.in#L13, but this is not an interactive shell, so according to the `bash(1)` manpage, `~/.bashrc` should not be sourced at all.

**Comment by rambip** [comment]
Ok, that's good to know.
So should I put this export before running the shell interactively, or add them into the path via another file ?

**Comment by rambip** [comment]
Ok, this is my fault, I puted an export statement that was important to my window manager in my bashrc instead of my bash_profile.

I guess we can close this issue now ...
