### ISSUE TITLE
Can a systemd user service depend on xlogin?

### ISSUE THREAD

**Issue by the-isz** [joukewitteveen/xlogin#5]
Hey guys,

I have a systemd user service which starts an X application. This service is configured to restart the X application should it crash. The service is automatically started in my user's session (which is created by xlogin).

Now, when I stop xlogin service, the X application is killed, but the service tries to restart it over and over again. Which of course fails, because there's no X anymore.

Is it possible to configure my service so that it is stopped when xlogin service is stopped?

Thanks in advance!

Timo

**Comment by joukewitteveen** [comment]
Is the `PartOf=` attribute of any use in your service?

**Comment by the-isz** [comment]
Hi Jouke,

thanks for your answer! I thought this wasn't possible, because systemd's user- and system-sessions are pretty strictly separated. However, I tried your suggestion and it does work indeed.

Now I just need to find out how to make my user service be stopped before xlogin, so that my X application doesn't crash because X is shutdown first...

Kind greetings,

Timo

**Comment by joukewitteveen** [comment]
IIRC that happens if you order your service `After=` the xlogin service.

**Comment by the-isz** [comment]
Hi Jouke,

again, thanks for your answer. Unfortunately, it seems that "After" doesn't
solve my issue. I can still see my X application crashing in systemd's log
before systemd stops the Default target in the user session.

Kind greetings,

Timo
