### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by rapgro** [joukewitteveen/xlogin#7]
Hi there,

it would be cool to have an official Fedora package. I could try with a review request, therefore we need a proper license with a license text file provided in the tarball.

As a good start, I would suggest a BSD based license, or MIT, but it's up to you to decide. (L)GPL version 2 or 3 is also valuable.

**Comment by joukewitteveen** [comment]
97667d7efe826c762d2b789ad5afc2c2516e44da

**Comment by rapgro** [comment]
Great! Thanks for the fast response. I'll suggest an official package for Fedora.

**Comment by rapgro** [comment]
Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1298715

See also #8

**Comment by joukewitteveen** [comment]
In your `.spec` file I saw the line
```
Requires:         xorg-x11-xinit
```
Please note that `xlogin` does not require `xinit`. All it requires is the Xorg server.

**Comment by rapgro** [comment]
Because:
```
$ rpm -qf /etc/X11/xinit/xinitrc.d
xorg-x11-xinit-1.3.4-10.fc23.x86_64
```
You reference that folder in README.
