### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rapgro** [joukewitteveen/xlogin#8]
Please add to service files:
```
Documentation=file:/usr/share/doc/xlogin/README
```

Maybe a nice manpage is also helpful for users.
```
Documentation=man:xlogin(8) file:/usr/share/doc/xlogin/README
```

**Comment by joukewitteveen** [comment]
Currently, we don't install the `README` and there is no man page. I am unsure whether writing one would be worthwhile as `xlogin` was really designed as a stop-gap solution. Using `.xinitrc`-defined sessions is a bit weird in a `systemd` setting and the way we managing environment variables (e.g. `DISPLAY`) and bus addresses shows just how imperfect the current landscape is. In my opinion this has more to do with lack of consensus in the `systemd` camp than with `xlogin`, which is also indicated by the fact that `xlogin` has been the best `workaround' for about four years now!

The part of `xlogin` that is not a hack is the `x-daemon` script which actually does something useful in an elegant way. This script, however, is under 100 bytes(!) so maybe it can serve as its own documentation. Admitted, every line uses something clever and non-trivial. In the end, it just spawns `X`, passing the command line arguments, and terminates when X is started. Does anyone desire documentation for that?
